/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function Home2(props) {
  return (
    <div className="bg-white flex flex-col items-stretch">
      <img
        loading="lazy"
        srcSet="..."
        className="aspect-[15.57] object-contain object-center w-full overflow-hidden max-md:max-w-full"
      />
      <div className="bg-indigo-50 w-full pt-4 pb-7 px-5 max-md:max-w-full">
        <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
          <div className="flex flex-col items-stretch w-[28%] max-md:w-full max-md:ml-0">
            <div className="flex items-stretch justify-between gap-3.5 max-md:mt-10">
              <div className="bg-sky-900 flex grow basis-[0%] flex-col items-stretch rounded-none">
                <div className="flex w-full flex-col pl-4 pr-1 pt-3 pb-10 rounded-none">
                  <div className="self-center flex w-[52px] max-w-full items-stretch gap-px">
                    <div className="text-white text-xl italic font-semibold">
                      REL
                    </div>
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/a4203c74-958c-4d40-bb6b-8f549d0e8bd7?"
                      className="aspect-[1.2] object-contain object-center w-full overflow-hidden shrink-0 flex-1"
                    />
                  </div>
                  <div className="shadow-sm bg-indigo-50 self-center flex w-[229px] max-w-full items-stretch gap-2 mt-3.5 pl-5 pr-9 py-4 rounded-[56px] max-md:pr-5">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/177fe630-c485-4982-a0a0-c21919c7600b?"
                      className="aspect-square object-contain object-center w-[13px] fill-sky-900 overflow-hidden shrink-0 max-w-full"
                    />
                    <div className="text-sky-900 text-sm font-medium whitespace-nowrap">
                      New Business Question
                    </div>
                  </div>
                  <div className="flex w-32 max-w-full items-stretch gap-1.5 ml-3 mt-6 self-start max-md:ml-2.5">
                    <div className="text-slate-400 text-xs">Today</div>
                    <div className="text-slate-400 text-xs whitespace-nowrap">
                      ( Water energy )
                    </div>
                  </div>
                  <div className="border self-center flex w-[229px] max-w-full items-stretch gap-2 mt-3.5 pl-7 pr-7 py-2.5 rounded-[56px] border-solid border-cyan-300 max-md:px-5">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/45b389fb-99a8-45f2-8c62-3b6ca27a109b?"
                      className="aspect-square object-contain object-center w-[9px] overflow-hidden shrink-0 max-w-full"
                    />
                    <div className="text-cyan-300 text-sm whitespace-nowrap">
                      Combine this Questions
                    </div>
                  </div>
                  <div className="text-cyan-300 text-opacity-60 text-center text-xs mt-2">
                    Combine the questions and get a global answer for all of
                    them in the same time
                  </div>
                  <div className="items-stretch bg-sky-950 self-stretch flex justify-between gap-5 mt-3 px-2 py-1 rounded-3xl max-md:justify-center">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/e5a3d465-64c7-46b9-8ef2-46bafdb1e5e6?"
                      className="aspect-square object-contain object-center w-[11px] fill-indigo-50 overflow-hidden self-center shrink-0 max-w-full my-auto"
                    />
                    <div className="text-indigo-50 text-sm">
                      Can the water energy i...
                    </div>
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/9d9677f9-99e1-4123-a964-10463d8cb888?"
                      className="aspect-[0.91] object-contain object-center w-2.5 fill-indigo-50 overflow-hidden self-center shrink-0 max-w-full my-auto"
                    />
                  </div>
                  <div className="flex gap-2 ml-2.5 mt-2 self-start">
                    <div className="flex basis-[0%] flex-col items-stretch">
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets/TEMP/161631cf-3a1b-4a6f-8eff-e10a83080f87?"
                        className="aspect-square object-contain object-center w-[11px] fill-indigo-50 overflow-hidden"
                      />
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets/TEMP/38216ac1-8a1d-486d-8e89-ecdad02d4ea3?"
                        className="aspect-square object-contain object-center w-[11px] fill-indigo-50 overflow-hidden mt-3.5"
                      />
                    </div>
                    <div className="self-stretch flex grow basis-[0%] flex-col items-stretch">
                      <div className="text-indigo-50 text-sm whitespace-nowrap">
                        Is the water energy can be sot imp
                      </div>
                      <div className="text-indigo-50 text-sm whitespace-nowrap mt-3">
                        How the water energy can be also
                      </div>
                    </div>
                  </div>
                  <div className="border self-center flex w-[229px] max-w-full items-stretch gap-2 mt-3.5 pl-4 pr-28 py-2.5 rounded-[56px] border-solid border-slate-400 max-md:pr-5">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/b70c1dff-d618-47a1-a762-a9e0bdf942a2?"
                      className="aspect-square object-contain object-center w-2.5 fill-slate-400 overflow-hidden shrink-0 max-w-full"
                    />
                    <div className="text-slate-400 text-xs whitespace-nowrap">
                      New Question
                    </div>
                  </div>
                  <div className="self-stretch flex items-stretch justify-between gap-0.5 mt-7 pr-2.5 max-md:justify-center">
                    <div className="text-slate-400 text-xs self-center my-auto">
                      Yesterday{" "}
                    </div>
                    <div className="text-slate-400 text-xs my-auto">
                      ( Electric energy )
                    </div>
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/d48f216d-aae9-435d-9f72-968d245905d5?"
                      className="aspect-square object-contain object-center w-[19px] overflow-hidden shrink-0 max-w-full"
                    />
                  </div>
                  <div className="self-stretch flex justify-between gap-2 mt-3.5">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/e7e9cc3f-920e-4e54-8c8a-9b11b73b7cdf?"
                      className="aspect-square object-contain object-center w-[11px] fill-indigo-50 overflow-hidden shrink-0 max-w-full"
                    />
                    <div className="text-indigo-50 text-sm self-stretch whitespace-nowrap">
                      Can the electric energy can sutbale
                    </div>
                  </div>
                  <div className="self-stretch flex justify-between gap-2 mt-3">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/aaafa3be-4fc0-4f9d-9e59-22e61d9138aa?"
                      className="aspect-square object-contain object-center w-[11px] fill-indigo-50 overflow-hidden shrink-0 max-w-full"
                    />
                    <div className="text-indigo-50 text-sm self-stretch whitespace-nowrap">
                      Is the water energy also with the wa
                    </div>
                  </div>
                  <div className="self-stretch flex justify-between gap-2 mt-3">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/8664befd-65bb-43b1-b920-427fc62fe0be?"
                      className="aspect-square object-contain object-center w-[11px] fill-indigo-50 overflow-hidden shrink-0 max-w-full"
                    />
                    <div className="text-indigo-50 text-sm self-stretch whitespace-nowrap">
                      How the electrical investing work w.
                    </div>
                  </div>
                  <div className="bg-slate-400 self-stretch shrink-0 h-px mt-96 max-md:mt-10" />
                  <div className="flex w-[189px] max-w-full items-stretch gap-2.5 ml-4 self-start max-md:ml-2.5">
                    <img
                      loading="lazy"
                      srcSet="..."
                      className="aspect-[1.12] object-contain object-center w-12 fill-indigo-50 opacity-10 overflow-hidden shrink-0 max-w-full"
                    />
                    <div className="text-indigo-50 text-sm self-center whitespace-nowrap my-auto">
                      Advanced functions{" "}
                    </div>
                  </div>
                  <div className="bg-slate-400 self-stretch shrink-0 h-px" />
                  <div className="self-stretch flex w-full items-stretch justify-between gap-5 mt-7">
                    <div className="flex items-stretch justify-between gap-2.5">
                      <img
                        loading="lazy"
                        srcSet="..."
                        className="aspect-square object-contain object-center w-[41px] overflow-hidden shrink-0 max-w-full rounded-[50%]"
                      />
                      <div className="text-indigo-50 text-sm font-medium self-center whitespace-nowrap my-auto">
                        Jhon sato
                      </div>
                    </div>
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/286e863c-46b1-43df-bf9e-5920c32a49d6?"
                      className="aspect-[6.5] object-contain object-center w-[13px] overflow-hidden self-center shrink-0 max-w-full my-auto"
                    />
                  </div>
                </div>
              </div>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/3c147d6b-f983-4418-8e65-2411455343fe?"
                className="aspect-square object-contain object-center w-10 overflow-hidden self-center shrink-0 max-w-full my-auto"
              />
            </div>
          </div>
          <div className="flex flex-col items-stretch w-[54%] ml-5 max-md:w-full max-md:ml-0">
            <div className="flex flex-col items-stretch mt-96 max-md:max-w-full max-md:mt-10">
              <div className="self-center flex w-[391px] max-w-full gap-2">
                <div className="text-sky-900 text-9xl italic font-semibold grow shrink basis-auto mt-2 max-md:text-4xl">
                  REL
                </div>
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/d1202c97-75f3-484c-aef3-091953350ea2?"
                  className="aspect-[1.15] object-contain object-center w-[135px] overflow-hidden self-stretch shrink-0 max-w-full"
                />
              </div>
              <div className="text-slate-500 text-4xl italic self-center whitespace-nowrap mt-2">
                Trusted resources user
              </div>
              <div className="shadow-sm bg-indigo-50 flex items-center justify-between gap-5 mt-96 pl-7 pr-8 py-5 rounded-[41px] max-md:max-w-full max-md:flex-wrap max-md:mt-10 max-md:px-5">
                <div className="text-slate-400 text-xs my-auto">
                  Send your question
                </div>
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/e6fba318-6c94-4629-b427-9a4fc007380a?"
                  className="aspect-square object-contain object-center w-[18px] overflow-hidden self-stretch shrink-0 max-w-full"
                />
              </div>
            </div>
          </div>
          <div className="flex flex-col items-stretch w-[19%] ml-5 max-md:w-full max-md:ml-0">
            <div className="flex w-full flex-col mx-auto pt-11 rounded-none border-2 border-solid border-slate-300 max-md:mt-10">
              <div className="text-sky-900 text-base font-medium self-center whitespace-nowrap">
                The Trusted Resources{" "}
              </div>
              <div className="bg-slate-400 self-center w-[252px] shrink-0 h-px mt-6" />
              <div className="text-slate-500 text-center text-xs mt-5">
                Defaultly all trusted resources will be selected and the related
                to your question ( business ) will be used to give you the best
                answer possible
              </div>
              <div className="bg-blue-100 self-center flex w-[228px] max-w-full items-stretch gap-1.5 mt-5 pl-3.5 pr-36 py-3 rounded-lg max-md:pr-5">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/5d76a621-5acb-4f4c-81b7-096b3b82885d?"
                  className="aspect-square object-contain object-center w-3 justify-center items-center overflow-hidden shrink-0 max-w-full"
                />
                <div className="text-slate-500 text-right text-xs whitespace-nowrap self-start">
                  Type to search...
                </div>
              </div>
              <div className="shadow-sm bg-indigo-50 self-center flex w-[228px] max-w-full items-center gap-2.5 mt-5 pl-3.5 pr-1.5 py-2.5 rounded-2xl">
                <img
                  loading="lazy"
                  srcSet="..."
                  className="aspect-[1.62] object-contain object-center w-[47px] overflow-hidden shrink-0 max-w-full my-auto"
                />
                <div className="flex grow basis-[0%] flex-col items-stretch self-start">
                  <div className="flex justify-between gap-5">
                    <div className="text-sky-900 text-xs font-medium mt-1.5">
                      NBC NEWS
                    </div>
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/cd16ddf2-0bb9-4a08-b328-bd3a16681cdf?"
                      className="aspect-square object-contain object-center w-[13px] overflow-hidden shrink-0 max-w-full"
                    />
                  </div>
                  <div className="text-slate-500 text-xs font-medium mt-2">
                    <span className="">
                      Nbc news is a trustworthy jornal news with an average of{" "}
                    </span>
                    <span className="font-medium">8.9</span>
                    <span className="">point</span>
                  </div>
                </div>
              </div>
              <div className="shadow-sm bg-indigo-50 self-center flex w-[228px] max-w-full items-center gap-4 mt-4 pl-3.5 pr-1.5 py-2.5 rounded-2xl">
                <img
                  loading="lazy"
                  srcSet="..."
                  className="aspect-[1.24] object-contain object-center w-[41px] overflow-hidden shrink-0 max-w-full my-auto"
                />
                <div className="flex grow basis-[0%] flex-col items-stretch self-start">
                  <div className="flex justify-between gap-5">
                    <div className="text-sky-900 text-xs font-medium mt-1.5">
                      NBC NEWS
                    </div>
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/f4484d31-0ac5-47e2-86c9-c912eb6293a7?"
                      className="aspect-square object-contain object-center w-[13px] overflow-hidden shrink-0 max-w-full"
                    />
                  </div>
                  <div className="text-slate-500 text-xs font-medium mt-2">
                    <span className="">
                      Nbc news is a trustworthy jornal news with an average of{" "}
                    </span>
                    <span className="font-medium">8.9</span>
                    <span className="">point</span>
                  </div>
                </div>
              </div>
              <div className="shadow-sm bg-indigo-50 self-center flex w-[228px] max-w-full flex-col mt-4 py-2.5 rounded-2xl">
                <div className="flex w-[149px] max-w-full justify-between gap-5">
                  <div className="text-sky-900 text-xs font-medium mt-2">
                    EPP electronic
                  </div>
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/8b1c14d5-ac43-4110-99e4-04a232af3712?"
                    className="aspect-square object-contain object-center w-[13px] overflow-hidden shrink-0 max-w-full"
                  />
                </div>
                <div className="self-stretch flex justify-between gap-2 mt-2">
                  <img
                    loading="lazy"
                    srcSet="..."
                    className="aspect-[2.88] object-contain object-center w-[46px] overflow-hidden shrink-0 max-w-full"
                  />
                  <div className="text-slate-500 text-xs font-medium">
                    <span className="">
                      Nbc news is a trustworthy jornal news with an average of{" "}
                    </span>
                    <span className="font-medium">8.9</span>
                    <span className="">point</span>
                  </div>
                </div>
              </div>
              <div className="shadow-sm bg-indigo-50 self-center flex w-[228px] max-w-full items-center gap-2.5 mt-4 pl-3.5 pr-1.5 py-2.5 rounded-2xl">
                <img
                  loading="lazy"
                  srcSet="..."
                  className="aspect-[1.62] object-contain object-center w-[47px] overflow-hidden shrink-0 max-w-full my-auto"
                />
                <div className="flex grow basis-[0%] flex-col items-stretch self-start">
                  <div className="flex justify-between gap-5">
                    <div className="text-sky-900 text-xs font-medium mt-1.5">
                      NBC NEWS
                    </div>
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/8760bf27-efb7-4184-9e3a-67b6fa8d1c10?"
                      className="aspect-square object-contain object-center w-[13px] overflow-hidden shrink-0 max-w-full"
                    />
                  </div>
                  <div className="text-slate-500 text-xs font-medium mt-2">
                    <span className="">
                      Nbc news is a trustworthy jornal news with an average of{" "}
                    </span>
                    <span className="font-medium">8.9</span>
                    <span className="">point</span>
                  </div>
                </div>
              </div>
              <div className="shadow-sm bg-indigo-50 self-center flex w-[228px] max-w-full items-center gap-4 mt-4 pl-3.5 pr-1.5 py-2.5 rounded-2xl">
                <img
                  loading="lazy"
                  srcSet="..."
                  className="aspect-[1.24] object-contain object-center w-[41px] overflow-hidden shrink-0 max-w-full my-auto"
                />
                <div className="flex grow basis-[0%] flex-col items-stretch self-start">
                  <div className="flex justify-between gap-5">
                    <div className="text-sky-900 text-xs font-medium mt-1.5">
                      NBC NEWS
                    </div>
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/0271c672-393d-4380-86ad-d917ef1361d5?"
                      className="aspect-square object-contain object-center w-[13px] overflow-hidden shrink-0 max-w-full"
                    />
                  </div>
                  <div className="text-slate-500 text-xs font-medium mt-2">
                    <span className="">
                      Nbc news is a trustworthy jornal news with an average of{" "}
                    </span>
                    <span className="font-medium">8.9</span>
                    <span className="">point</span>
                  </div>
                </div>
              </div>
              <div className="shadow-sm bg-indigo-50 self-center flex w-[228px] max-w-full flex-col mt-4 py-2.5 rounded-2xl">
                <div className="flex w-[149px] max-w-full justify-between gap-5">
                  <div className="text-sky-900 text-xs font-medium mt-2">
                    EPP electronic
                  </div>
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/610c0dfb-5fd8-4ba8-9d3b-e04f5b5cd765?"
                    className="aspect-square object-contain object-center w-[13px] overflow-hidden shrink-0 max-w-full"
                  />
                </div>
                <div className="self-stretch flex justify-between gap-2 mt-2">
                  <img
                    loading="lazy"
                    srcSet="..."
                    className="aspect-[2.88] object-contain object-center w-[46px] overflow-hidden shrink-0 max-w-full"
                  />
                  <div className="text-slate-500 text-xs font-medium">
                    <span className="">
                      Nbc news is a trustworthy jornal news with an average of{" "}
                    </span>
                    <span className="font-medium">8.9</span>
                    <span className="">point</span>
                  </div>
                </div>
              </div>
              <div className="shadow-sm bg-indigo-50 self-center flex w-[228px] max-w-full items-center gap-3 mt-4 pl-5 pr-1.5 py-2.5 rounded-2xl">
                <img
                  loading="lazy"
                  srcSet="..."
                  className="aspect-[1.17] object-contain object-center w-[41px] overflow-hidden shrink-0 max-w-full my-auto"
                />
                <div className="flex grow basis-[0%] flex-col items-stretch self-start">
                  <div className="flex justify-between gap-5">
                    <div className="text-sky-900 text-xs font-medium mt-2">
                      Electronics
                    </div>
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/0e1a5093-5116-4879-a8d0-ad5a0c5dbad4?"
                      className="aspect-square object-contain object-center w-[13px] overflow-hidden shrink-0 max-w-full"
                    />
                  </div>
                  <div className="text-slate-500 text-xs font-medium mt-2">
                    <span className="">
                      Nbc news is a trustworthy jornal news with an average of{" "}
                    </span>
                    <span className="font-medium">8.9</span>
                    <span className="">point</span>
                  </div>
                </div>
              </div>
              <div className="flex-col fill-[linear-gradient(0deg,#E7F4FF_53.94%,rgba(231,244,255,0.00)_126.39%)] overflow-hidden self-stretch relative flex aspect-[2.088235294117647] w-full items-stretch pl-8 pr-6 pt-5 pb-7 max-md:px-5">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/74690344-6734-410c-980a-a08a5898b61e?"
                  className="absolute z-[-1] h-full w-full object-cover object-center inset-0"
                />
                <div className="relative shadow-sm bg-indigo-50 flex w-full flex-col py-2.5 rounded-2xl">
                  <div className="flex w-[149px] max-w-full justify-between gap-5">
                    <div className="text-sky-900 text-xs font-medium mt-2">
                      EPP electronic
                    </div>
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/b71586e0-3a49-4ae6-b094-635b5936e07a?"
                      className="aspect-square object-contain object-center w-[13px] overflow-hidden shrink-0 max-w-full"
                    />
                  </div>
                  <div className="self-stretch flex justify-between gap-2 mt-2">
                    <img
                      loading="lazy"
                      srcSet="..."
                      className="aspect-[2.88] object-contain object-center w-[46px] overflow-hidden shrink-0 max-w-full"
                    />
                    <div className="text-slate-500 text-xs">
                      Nbc news is a trustworthy jornal news with an average of
                      8.9point
                    </div>
                  </div>
                </div>
                <div className="relative text-sky-900 text-center text-xs z-[1] mt-0">
                  Important Note : You can element some resources if you think
                  its not good for you!
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
export default Home2;
